openapi: 3.0.3
info:
  title: Product IT Assessment
  description: API documentation for the Survey Application, including User, Question, and Assessment services.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server
tags:

  - name: Question
    externalDocs:
      description: Find out more
      url: http://swagger.io

  - name: Survey
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /assessments/{setname}/{qid}:
    put:
      tags:
        - Question
      summary: Update a question based on id
      parameters:
        - name: setname
          in: path
          required: true
          schema:
            type: string
        - name: qid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                  example: domain1
                qdetails:
                  type: string
                  example: What is your full name?
                answers:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        example: answer1_id
                      answer:
                        type: string
                        example: answer1
                      suggestions:
                        type: string
                createdby:
                  type: string
                  example: JohnDoe
                modified_at:
                  type: string
                  format: date-time
                  example: "2024-08-01T12:00:00Z"
      responses:
        '200':
          description: Question updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  setname:
                    type: string
                    example: ExampleSet
                  qid:
                    type: string
                    example: q1
                  updatedQuestion:
                    type: object
                    properties:
                      domain:
                        type: string
                        example: domain1
                      qdetails:
                        type: string
                        example: What is your full name?
                      answers:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: answer1_id
                            answer:
                              type: string
                              example: answer1
                            suggestions:
                              type: string
                              example: suggestion1
                                    
                      createdby:
                        type: string
                        example: JohnDoe
                      created_at:
                        type: string
                        format: date-time
                        example: "2024-08-01T12:00:00Z"
                      modified_at:
                        type: string
                        format: date-time
                        example: "2024-08-01T12:00:00Z"


    delete:
      tags:
        - Question
      summary: Delete an question based on its id
      parameters:
        - name: setname
          in: path
          required: true
          schema:
            type: string
        - name: qid
          in: path
          required: true
          schema:
            type: string
        
      responses:
        '200':
          description: Question deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  setname:
                    type: string
                    example: ExampleSet
                  qid:
                    type: string
                    example: q1
                  updatedQuestion:
                    type: object
                    properties:
                      domain:
                        type: string
                        example: domain1
                      qdetails:
                        type: string
                        example: What is your full name?
                      answers:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: answer1_id
                            answer:
                              type: string
                              example: answer1
                            suggestions:
                              type: string
                              example: suggestion1
                                    
                      createdby:
                        type: string
                        example: JohnDoe
                      created_at:
                        type: string
                        format: date-time
                        example: "2024-08-01T12:00:00Z"
                      modified_at:
                        type: string
                        format: date-time
                        example: "2024-08-01T12:00:00Z"
                

  /assessments/setname:
    post:
      tags:
        - Question
      summary: Post a set of questions

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                  example: exampleDomain
                setname:
                  type: string
                  example: ExampleSet
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      qid:
                        type: string
                        example: q1
                      createdby:
                        type: string
                        example: JohnDoe
                        
                      qdetails:
                        type: string
                        example: What is your name?
                      answers:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: answer1_id
                            answer:
                              type: string
                              example: answer1
                            suggestions:
                              type: string
                              example: suggestion1
                      
                      created_at:
                        type: string
                        format: date-time
                        example: "2024-08-01T12:00:00Z"
                      modified_at:
                        type: string
                        format: date-time
                        example: "2024-08-01T12:00:00Z"
      responses:
        '200':
          description: Questions posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  setname:
                    type: string
                    example: ExampleSet
                    
  /assessments/{setname}:
    get:
      tags:
        - Question
      summary: Retrieve questions for a setname
      parameters:
        - name: setname
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Questions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  setname:
                    type: string
                    example: ExampleSet
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        qid:
                          type: string
                          example: q1
                        createdby:
                          type: string
                          example: JohnDoe
                        domain:
                          type: string
                          example: domain1
                        qdetails:
                          type: string
                          example: What is your name?
                        answers:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                example: answer1_id
                              answer:
                                type: string
                                example: answer1
                              suggestions:
                                type: string
                        created_at:
                          type: string
                          format: date-time
                          example: "2024-08-01T12:00:00Z"
                        modified_at:
                          type: string
                          format: date-time
                          example: "2024-08-01T12:00:00Z"
                  
                          
  

                    
                    
  /assessments:
    get:
      tags:
        - Question
      summary: Get all assessments
     
      responses:
        '200':
          description: Assessments retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    aid:
                      type: string
                      example: assessment1
                    setname:
                      type: string
                      example: ExampleSet
                    createdby:
                      type: string
                      example: JohnDoe
                    domain:
                      type: string
                      example: domain1
                    status:
                      type: string
                      example: active
                    cname:
                      type: string
                      example: CompanyA
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          qid:
                            type: string
                            example: q1
                          domain:
                            type: string
                            example: domain1
                          qdetails:
                            type: string
                            example: What is your name?
                          answers:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: string
                                  example: answer1_id
                                answer:
                                  type: string
                                  example: answer1
                                suggestions:
                                  type: string
                                  
                      
                          created_at:
                            type: string
                            format: date-time
                            example: "2024-08-01T12:00:00Z"
                          modified_at:
                            type: string
                            format: date-time
                            example: "2024-08-01T12:00:00Z"
                  
                        
                        
  /survey:
    post:
      tags:
        - Survey
      summary: Add details to the survey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                surveyid:
                  type: integer
                  example: 1
                cname:
                  type: string
                  example: ExampleCompany
                cemail:
                  type: string
                  example: contact@example.com
                domain:
                  type: string
                  example: exampleDomain
                setname:
                  type: string
                  example: ExampleSet
                createdby:
                  type: string
                  example: John Doe
                status:
                  type: string
                  enum: [intiated,pending,accepted,rejected]
                  example: intiated
              required:
                - surveyid
                - cname
                - cemail
                - domain
                - setname
                - createdby
                - status
      responses:
        '201':
          description: Details added successfully
        '400':
          description: Bad request, invalid input
        '404':
          description: Not found, endpoint or resource not available
        '500':
          description: Internal server error

    get:
      tags:
        - Survey
      summary: Retrieve all details from the survey
      responses:
        '200':
          description: Details retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    surveyid:
                      type: integer
                      example: 1
                    cname:
                      type: string
                      example: ExampleCompany
                    cemail:
                      type: string
                      example: contact@example.com
                    domain:
                      type: string
                      example: exampleDomain
                    setname:
                      type: string
                      example: ExampleSet
                    createdby:
                      type: string
                      example: John Doe
                    status:
                      type: string
                      enum: [intiated,pending,accepted,rejected]
                      example: intiated
  
  /survey/{surveyid}:
    get:
      tags:
        - Survey
      summary: Get a survey by ID
      description: Retrieves a survey using the specified ID.
      parameters:
        - name: surveyid
          in: path
          required: true
          description: The ID of the survey to retrieve.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successfully retrieved the survey
          content:
            application/json:
              schema:
                type: object
                properties:
                  surveyid:
                    type: integer
                    example: 1
                  cname:
                    type: string
                    example: ExampleCompany
                  cemail:
                    type: string
                    example: contact@example.com
                  domain:
                    type: string
                    example: exampleDomain
                  setname:
                    type: string
                    example: ExampleSet
                  createdby:
                    type: string
                    example: John Doe
                  status:
                    type: string
                    enum: [intiated,pending,accepted,rejected]
                    example: intiated
        '404':
          description: Survey not found
          content:
            text/plain:
              schema:
                type: string
                example: Survey not found


